networks:
  - name: mgmt
    backend: vale
    interfaces:     # ou 'ports:'
      - if: em0
      - if: vether0

  - name: core
    backend: netgraph
    interfaces:
      - if: lsd0
      - if: lsd1
